<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Simulation\Simulation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Plotly.NET.CSharp" Version="0.12.0" />
    <PackageReference Include="Plotly.NET.ImageExport" Version="6.0.0" />
  </ItemGroup>

</Project>
